18-rails-associations/dog-tracker/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dogs, only: [:show, :index, :new, :create, :edit, :update]
  resources :parks, only: [:index, :show]
  resources :visits, only: [:new, :create]
end

18-rails-associations/dog-tracker/app/models/dog.rb
class Dog < ApplicationRecord

  has_many :visits
  has_many :parks, through: :visits

  # has_and_belongs_to_many :parks

  CAT_NAMES = ["Fluffy", "Martha", "Elliott", "Garfield"]

  validates :name, presence: true
  validates :tail_length, presence: true, numericality: { 
      less_than_or_equal_to: 12, 
      greater_than: 0 
    }


  validate :no_cat_names

  def no_cat_names
    if self.name && CAT_NAMES.map(&:downcase).include?(self.name.downcase)
      self.errors.add(:name, "can't be a cat name 🙅‍♂️😸")
    end
  end

  # validates(:name, { presence: true })


end

18-rails-associations/dog-tracker/app/models/park.rb
class Park < ApplicationRecord
end

18-rails-associations/dog-tracker/app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :dog
  belongs_to :park
end

18-rails-associations/dog-tracker/app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  # before_action(:get_dog, { only: [:show, :edit] })
  
  before_action :get_dog, only: [:show, :edit, :update]

  def index
    @dogs = Dog.all
  end

  def show
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.create(dog_params)
    if @dog.valid?
      redirect_to @dog
    else
      render :new
      # redirect_to new_dog_path
    end
  end

  def edit
  end

  def update
    if @dog.update(dog_params)
      redirect_to @dog
    else
      render :edit
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :tail_length, :color_hexadecimal)
  end

  def get_dog
    @dog = Dog.find(params[:id])
  end

end

18-rails-associations/dog-tracker/app/controllers/parks_controller.rb
class ParksController < ApplicationController
  
  before_action :get_park, only: [:show]

  def index
    @parks = Park.all
  end

  def show
  end


  private

  def get_park
    @park = Park.find(params[:id])
  end

end

18-rails-associations/dog-tracker/app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def new
    get_form_stuff
    @visit = Visit.new
  end

  def create
    @visit = Visit.create(visit_params)
    if @visit.valid?
      redirect_to @visit.dog
    else
      get_form_stuff
      render :new
    end
  end

  private

  def get_form_stuff
    @all_dogs = Dog.all
    @all_parks = Park.all
  end

  def visit_params
    params.require(:visit).permit(:dog_id, :park_id)
  end
end

18-rails-associations/dog-tracker/app/views/dogs/_form.erb
<ul style="color: red;">
  <% @dog.errors.full_messages.each do |message| %>
  <li>
    <%= message %>
  </li>
  <% end %>
</ul>

<%= form_for @dog do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :tail_length %>
  <%= form.number_field :tail_length %>

  <%= form.label :color_hexadecimal %>
  <%= form.text_field :color_hexadecimal %>

  <%= form.submit %>

<% end %>

18-rails-associations/dog-tracker/app/views/dogs/edit.erb
<h1>Editing <%= @dog.name %></h1>

<%= render "form" %>

<!-- 
<form action="/dogs/<%= @dog.id %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">

  <label for="name">Name:</label>
  <input id="name" type="text" name="dog[name]"></input>
</form> 
<%= form_tag dog_path, method: :patch do %>

  <%= label_tag :name %>
  <%= text_field_tag :name, @dog.name %>

<% end %>

<%= form_for Dog.new do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.submit %>

<% end %>

-->

18-rails-associations/dog-tracker/app/views/dogs/index.erb
<h1>All the dogs</h1>
<ul>
  <% @dogs.each do |dog| %>
  <li>
    <%= link_to dog.name, dog %>
  </li>
  <% end %>
</ul>

18-rails-associations/dog-tracker/app/views/dogs/new.erb
<h1>New Dog</h1>

<%= render "form" %>

18-rails-associations/dog-tracker/app/views/dogs/show.erb
<h1><%= @dog.name %></h1>

<ol>
  <li>
Tail Length: <%= @dog.tail_length %> foot
</li>
<li>
Color: <span class="swatch" background="<%= @dog.color_hexadecimal %>"></span>
</li>
</ol>


<ul>
  <% @dog.parks.each do |park| %>
  <li>
    <%= link_to park.name, park %>
  </li>
  <% end %>
</ul>

<%# link_to "Edit #{ @dog.name }", "/dogs/#{ @dog.id }/edit" %>
<footer>
<%= link_to "Edit #{ @dog.name }", edit_dog_path(@dog) %>
</footer>

18-rails-associations/dog-tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

18-rails-associations/dog-tracker/app/views/visits/new.erb
<h1>New Visit</h1>

<ul style="color: red;">
  <% @visit.errors.full_messages.each do |message| %>
  <li>
    <%= message %>
  </li>
  <% end %>
</ul>


<%= form_for @visit do |f| %>

  <%= f.label :dog_id %>
  <%= f.collection_select :dog_id, @all_dogs, :id, :name %>
  <%# f.text_field :dog_id %>
<!--   <select name=visit[dog_id]>
    <option value="1">Clifford</option>
    <option value="2">Balto</option>
  </select> -->
  <%= f.label :park_id %>
  <%= f.collection_select :park_id, @all_parks, :id, :name, { prompt: "Select a park..." } %>

  <%# f.text_field :park_id %>


  <%= f.submit %>
<% end %>